export const projectsArray = [
  {
    id: 1,
    Name: "TachShop",
    Description: "Ecommerce Mern website",
    imageSrc: "/assets/tachshop.png",
    Technologies: ["React", "Tailwind", "HTML", "CSS", "JavaScript", "GSAP"],
    bgimage: "/assets/tachshop.png",
    LinkGit: "https://tachshop.onrender.com/",
    code: "https://github.com/MohammadHarish52/Tachshop",
  },
  {
    id: 2,
    Name: "Aesop Ui",
    Description: "Clone Homepage of Aesop",
    imageSrc: "/assets/Aesop.png",
    Technologies: ["React", "Tailwind", "HTML", "CSS", "JavaScript"],
    bgimage: "/assets/Aesopbg.png",
    LinkGit: "https://timely-chaja-21ff77.netlify.app/",
    code: "https://github.com/MohammadHarish52/Aesop",
  },
  {
    id: 3,
    Name: "Movie Ticket App",
    Description: "Dummy Movie ticket Booking",
    imageSrc: "/assets/Movie-App.png",
    bgimage: "/assets/moviebg.png",
    Technologies: ["HTML", "CSS", "JavaScript"],
    LinkGit: "https://two-screen-vxt7.vercel.app/",
    code: "https://github.com/MohammadHarish52/Two-screen",
  },
  {
    id: 4,
    Name: "Amazon Clone",
    Description: "Clone Homepage of Amazon",
    imageSrc: "/assets/Amazon.png",
    bgimage: "/assets/amazonbg.png",
    Technologies: ["HTML", "CSS", "JavaScript"],
    LinkGit: "https://mohammadharish52.github.io/amazoncloneui/",
    code: "https://github.com/MohammadHarish52/amazoncloneui/tree/main",
  },
  {
    id: 5,
    Name: "Weather App",
    Description: "Simple weather App",
    imageSrc: "/assets/WeatherApp.png",
    bgimage: "/assets/Weatherbg.png",
    Technologies: ["React", "API"],
    LinkGit: "https://mohammadharish52.github.io/weather-app/",
    code: "https://github.com/MohammadHarish52/weather-app",
  },
  {
    id: 6,
    Name: "Meme Generator",
    Description: "Fun Random meme generator",
    imageSrc: "/assets/meme.png",
    bgimage: "/assets/meme.png",
    Technologies: ["HTML", "CSS", "JavaScript"],
    LinkGit: "https://umemes.vercel.app/",
    code: "https://github.com/MohammadHarish52/randommemegenrator",
  },
  {
    id: 7,
    Name: "Currency Convertor",
    Description: "A simple currency converter",
    imageSrc: "/assets/CurrencyConverter.png",
    bgimage: "/assets/currency.png",
    Technologies: ["HTML", "CSS", "JavaScript", "API"],
    LinkGit: "https://mohammadharish52.github.io/Currency-converter/",
    code: "https://github.com/MohammadHarish52/currency-converter",
  },
  {
    id: 8,
    Name: "Snake Snezia",
    Description: "Simple snake game",
    imageSrc: "/assets/tdl.png",
    bgimage: "/assets/snake.png",
    Technologies: ["HTML", "CSS", "JavaScript"],
    LinkGit: "https://snakegame-lyart-pi.vercel.app/",
    code: "https://github.com/MohammadHarish52/Ex-game",
  },
  {
    id: 9,
    Name: "Flappy Bird",
    Description: "Bring Physics to Web",
    imageSrc: "/assets/RockPaperScissors.png",
    bgimage: "/assets/flappybird.png",
    Technologies: ["HTML", "CSS", "JavaScript"],
    LinkGit: "https://flappybird-beta.vercel.app/",
    code: "https://github.com/MohammadHarish52/flop-ball",
  },
  // Add more projects as needed
];
