export const freelanceArray = [
  {
    id: 1,
    Name: "Fast & Fab",
    bgimage: "/assets/fastfab.png",
    bgDarkImage: "/assets/fastfab.png",
    LinkGit: "https://fastandfab.in/",
    Description: "Fast Fashion website",
  },
  {
    id: 2,
    Name: "Beyond Dreams",
    bgimage: "/assets/beyonddream.png",
    bgDarkImage: "/assets/beyonddream.png",
    LinkGit: "https://www.beyonddream.in/user",
    Description: "Tech events and conferences website",
  },
  {
    id: 3,
    Name: "E-Legalify",
    bgimage: "/assets/elegalify.png",
    bgDarkImage: "/assets/elegalify.png",
    LinkGit: "https://freelance-1-one.vercel.app/",
    Description: "Legal website for lawyers",
  },

  {
    id: 4,
    Name: "Memansa ",
    bgimage: "/assets/memansa.png",
    bgDarkImage: "/assets/memansa.png",
    LinkGit: "https://memansa.vercel.app/",
    Description: "Accessories design website",
  },
  {
    id: 5,
    Name: "instaChip",
    bgimage: "/assets/instachip.png",
    bgDarkImage: "/assets/instachip.png",
    LinkGit: "https://residency-client.vercel.app/",
    Description: "Restaurant management system",
  },
  {
    id: 6,
    Name: "LetsGrowEsports",
    bgimage: "/assets/letsgrowesprots.png",
    bgDarkImage: "/assets/letsgrowesprots.png",
    LinkGit: "https://letsgrowesports.vercel.app/",
    Description: "Restaurant management system",
  },
];
