export const freelanceArray = [
  {
    id: 1,
    Name: "E-Legalify",
    bgimage: "/assets/elegalify.png",
    bgDarkImage: "/assets/elegalifydark.png",
    LinkGit: "https://freelance-1-one.vercel.app/",
    code: "https://github.com/MohammadHarish52/freelance-1e",
    Description: "Legal website for lawyers",
  },
  {
    id: 2,
    Name: "Memansa ",
    bgimage: "/assets/memansa.png",
    bgDarkImage: "/assets/memansadark.png",
    LinkGit: "https://memansa.vercel.app/",
    code: "https://github.com/MohammadHarish52/memansa",
    Description: "Accessories design website",
  },
  {
    id: 3,
    Name: "instaChip",
    bgimage: "/assets/instachip.png",
    bgDarkImage: "/assets/instachipdark.png",
    LinkGit: "https://residency-client.vercel.app/",
    code: "https://github.com/MohammadHarish52/residency-client",
    Description: "Restaurant management system",
  },
  {
    id: 4,
    Name: "LetsGrowEsports",
    bgimage: "/assets/instachip.png",
    bgDarkImage: "/assets/instachipdark.png",
    LinkGit: "https://letsgrowesports.vercel.app/",
    code: "https://github.com/MohammadHarish52/residency-client",
    Description: "Restaurant management system",
  },
];
