export const projectsArray = [
  {
    id: 1,
    Name: "Aesop Ui",
    Description: "Clone Homepage of Aesop",
    imageSrc: "/public/assets/Projectimages/Aesop.png",
    Technologies: ["React", "Tailwind", "HTML", "CSS", "JavaScript"],
    bgimage: "/public/assets/Projectimages/Aesopbg.png",
    LinkGit: "https://timely-chaja-21ff77.netlify.app/",
    code: "https://github.com/MohammadHarish52/Aesop",
  },
  {
    id: 2,
    Name: "Movie Ticket App",
    Description: "Dummy Movie ticket Booking",
    imageSrc: "/public/assets/Projectimages/Movie-App.png",
    bgimage: "/public/assets/Projectimages/moviebg.png",
    Technologies: ["HTML", "CSS", "JavaScript"],
    LinkGit: "https://two-screen-vxt7.vercel.app/",
    code: "https://github.com/MohammadHarish52/Two-screen",
  },
  {
    id: 3,
    Name: "Amazon Clone",
    Description: "Clone Homepage of Amazon",
    imageSrc: "/public/assets/Projectimages/Amazon.png",
    bgimage: "/public/assets/Projectimages/amazonbg.png",
    Technologies: ["HTML", "CSS", "JavaScript"],
    LinkGit: "https://mohammadharish52.github.io/amazoncloneui/",
    code: "https://github.com/MohammadHarish52/amazoncloneui/tree/main",
  },
  {
    id: 4,
    Name: "Weather App",
    Description: "Simple weather App",
    imageSrc: "/public/assets/Projectimages/WeatherApp.png",
    bgimage: "/public/assets/Projectimages/weatherbg.png",
    Technologies: ["React", "API"],
    LinkGit: "https://mohammadharish52.github.io/weather-app/",
    code: "https://github.com/MohammadHarish52/weather-app",
  },
  {
    id: 5,
    Name: "Meme Generator",
    Description: "Fun Random meme generator",
    imageSrc: "/public/assets/Projectimages/meme.png",
    bgimage: "/public/assets/Projectimages/meme.png",
    Technologies: ["HTML", "CSS", "JavaScript"],
    LinkGit: "https://umemes.vercel.app/",
    code: "https://github.com/MohammadHarish52/color-generator",
  },
  {
    id: 6,
    Name: "Currency Convertor",
    Description: "A simple currency converter",
    imageSrc: "/public/assets/Projectimages/CurrencyConverter.png",
    bgimage: "/public/assets/Projectimages/currency.png",
    Technologies: ["HTML", "CSS", "JavaScript", "API"],
    LinkGit: "https://mohammadharish52.github.io/Currency-converter/",
    code: "https://github.com/MohammadHarish52/currency-converter",
  },
  {
    id: 7,
    Name: "Snake Snezia",
    Description: "Simple snake game",
    imageSrc: "/public/assets/Projectimages/tdl.png",
    bgimage: "/public/assets/Projectimages/snake.png",
    Technologies: ["HTML", "CSS", "JavaScript"],
    LinkGit: "https://snakegame-lyart-pi.vercel.app/",
    code: "https://github.com/MohammadHarish52/todo-list",
  },
  {
    id: 8,
    Name: "Flappy Bird",
    Description: "Bring Physics to Web",
    imageSrc: "/public/assets/Projectimages/RockPaperScissors.png",
    bgimage: "/public/assets/Projectimages/flappybird.png",
    Technologies: ["HTML", "CSS", "JavaScript"],
    LinkGit: "https://flappybird-beta.vercel.app/",
    code: "https://github.com/MohammadHarish52/rock-paper-scissors",
  },
  // Add more projects as needed
];
