export const uiuxArray = [
  {
    id: 1,
    Name: "UI Hackathon",
    Description: "Selected UI screens and interactions",
    bgDarkImage: "/assets/uihack.png",
    bgimage: "/assets/uihack.png",
    LinkGit: "https://ui-hackathon-jam.vercel.app/",
  },
  {
    id: 2,
    Name: "Salfiya",
    Description: "Portfolio website for a friend",
    bgDarkImage: "/assets/salfiya.png",
    bgimage: "/assets/salfiya.png",
    LinkGit: "https://salfiya.sh/",
  },

  {
    id: 3,
    Name: "Elegance",
    Description: "Cosmetic showcase UI website",
    bgDarkImage: "/assets/elegance.png",
    bgimage: "/assets/elegen.png",
    LinkGit: "https://elegance-orpin.vercel.app/",
  },
  {
    id: 3,
    Name: "Panekka",
    Description: "Recipe UI",
    bgDarkImage: "/assets/panekka.png",
    bgimage: "/assets/panekka.png",
    LinkGit: "https://pankekka-website.vercel.app/",
  },
  {
    id: 4,
    Name: "Perfectly Scaled",
    Description: "Product visualization UI",
    bgDarkImage: "/assets/perfectscaled.png",
    bgimage: "/assets/perfectscaled.png",
    LinkGit: "https://perfect-scaled.vercel.app/",
  },
  {
    id: 5,
    Name: "Funky Tweets",
    Description: "Twitter-inspired UI",
    bgDarkImage: "/assets/funkytweets.png",
    bgimage: "/assets/funkytweets.png",
    LinkGit: "https://funky-tweet-vibes.vercel.app/",
  },
  {
    id: 6,
    Name: "Aesop UI",
    Description: "Aesop homepage clone",
    bgDarkImage: "/assets/aesop.png",
    bgimage: "/assets/aesop.png",
    LinkGit: "https://timely-chaja-21ff77.netlify.app/",
  },
  {
    id: 7,
    Name: "FocusFeed",
    Description: "News media UI",
    bgDarkImage: "/assets/focusfeed.png",
    bgimage: "/assets/focusfeed.png",
    LinkGit: "https://focusfeed-daily-glance.vercel.app/",
  },
];
